# Generated by Django 4.0.6 on 2025-01-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_perfilusuario_libro_disponible_alter_libro_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Vendedor', 'Vendedor'), ('Comprador', 'Comprador')], default='Comprador', max_length=50),
        ),
    ]
