# Generated by Django 4.0.6 on 2025-01-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_perfilusuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='estado',
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
